---
kind: pipeline
type: docker
name: build-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: build-and-package
    image: docker
    environment: &environment
      _EXPERIMENTAL_DAGGER_CLOUD_TOKEN:
        from_secret: dagger_cloud_token
      _EXPERIMENTAL_DAGGER_CACHE_CONFIG:
        from_secret: dagger_cache_config
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      GH_TOKEN:
        from_secret: github_token
    volumes: &volumes
      - name: dagger-bin
        path: /dagger-bin
      - name: docker-sock
        path: /var/run/docker.sock
      - name: docker-config
        path: /root/.docker
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults
    when:
      instance:
        - drone-publish.rancher.io
  - name: build-and-package-pr
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults --coverage.export=true
    when:
      instance:
        - drone-pr.rancher.io
  - name: publish-tag
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults,dagger/ci/push,dagger/ci/push-charts,dagger/ci/tag-latest
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
  - name: publish-main
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults,dagger/ci/push
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
  - name: upload-coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - cover.out
    when:
      event:
        - push
      instance:
        - drone-pr.rancher.io
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-config
    host:
      path: /root/.docker
