---
kind: pipeline
type: docker
name: build-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: setup-dagger-engine
    image: docker
    commands:
      - |
        docker run \
        --name dagger-engine \
        --privileged \
        --stop-signal SIGTERM \
        -d \
        -e _EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN=$_EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN \
        -e _EXPERIMENTAL_DAGGER_CACHESERVICE_URL=https://api.dagger.cloud/magicache \
        -v dagger-engine:/var/lib/dagger \
        registry.dagger.io/engine:main || docker start dagger-engine
    volumes: &volumes
      - name: docker-sock
        path: /var/run/docker.sock
      - name: docker-config
        path: /root/.docker
    environment:
      _EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN:
        from_secret: dagger_cacheservice_token
  - name: build-and-package
    image: docker
    environment: &environment
      _EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN:
        from_secret: dagger_cacheservice_token
      _EXPERIMENTAL_DAGGER_CLOUD_TOKEN:
        from_secret: dagger_cloud_token
      _EXPERIMENTAL_DAGGER_RUNNER_HOST: docker-container://dagger-engine
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      GH_TOKEN:
        from_secret: github_token
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults
    when:
      instance:
        - drone-publish.rancher.io
  - name: build-and-package-pr
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults --coverage.export=true
    when:
      instance:
        - drone-pr.rancher.io
  - name: publish-tag
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults,dagger/ci/push,dagger/ci/push-charts,dagger/ci/tag-latest
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
      refs:
        - refs/heads/main
        - refs/heads/release
        - refs/tags/*
  - name: publish-main
    image: docker
    environment: *environment
    volumes: *volumes
    commands:
      - apk add --no-cache go
      - go run ./dagger -c dagger/ci/defaults,dagger/ci/push
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      branch:
        - main
  - name: upload-coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - cover.out
    when:
      event:
        - push
      instance:
        - drone-pr.rancher.io
  - name: cleanup-dagger-engine
    image: docker
    commands:
      - docker stop --time 60 dagger-engine
      - docker logs dagger-engine
    volumes: *volumes
    # run even if pipeline fails
    when:
      status:
        - failure
        - success
      instance:
        - drone-publish.rancher.io
        - drone-pr.rancher.io
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: docker-config
    host:
      path: /root/.docker
