{{- if .Values.gateway.enabled }}
apiVersion: core.monty.io/v1
kind: Gateway
metadata:
  name: monty-gateway
  namespace: {{ include "monty.namespace" . }}
  labels:
    {{- include "monty.labels" . | nindent 4 }}
spec:
  {{- if .Values.image.tag }}
  agentImageTagOverride: {{ .Values.image.tag }}
  {{- end }}
  serviceType: {{ .Values.gateway.serviceType }}
  natsCluster:
    name: monty
  {{- with .Values.gateway.serviceAnnotations }}
  serviceAnnotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.extraVolumeMounts }}
  extraVolumeMounts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}