
url: local
version: 0.9.1
workingDir: charts
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
    addCRDValidationToMainChart: false