annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: monty-crd
  catalog.cattle.io/namespace: monty
  catalog.cattle.io/display-name: Monty CRDs
apiVersion: v1
version: 0.5.4
description: Installs the CRDs for Monty.
name: monty-crd
type: application
maintainers:
- email: joe.kralicky@suse.com
  name: Joe Kralicky
- email: dan.bason@suse.com
  name: Dan Bason
