# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - opensearch/opensearch.opster.io_opensearchclusters.yaml
  - opensearch/opensearch.opster.io_opensearchroles.yaml
  - grafana/grafana.monty.io_grafanadashboards.yaml
  - grafana/grafana.monty.io_grafanadatasources.yaml
  - grafana/grafana.monty.io_grafanas.yaml
  - bases/ai.monty.io_montyclusters.yaml
  - bases/ai.monty.io_pretrainedmodels.yaml
  - bases/core.monty.io_bootstraptokens.yaml
  - bases/core.monty.io_keyrings.yaml
  - bases/core.monty.io_gateways.yaml
  - bases/core.monty.io_loggingclusters.yaml
  - bases/core.monty.io_monitoringclusters.yaml
  - bases/core.monty.io_alertingclusters.yaml
  - bases/core.monty.io_natsclusters.yaml
  #- bases/core.monty.io_collectors.yaml
  - bases/logging.monty.io_datapreppers.yaml
  - bases/logging.monty.io_logadapters.yaml
  - bases/logging.monty.io_loggingclusterbindings.yaml
  - bases/logging.monty.io_multiclusterrolebindings.yaml
  - bases/logging.monty.io_multiclusterusers.yaml
  - bases/logging.monty.io_montyopensearches.yaml
  - bases/logging.monty.io_opensearchrepositories.yaml
  - bases/logging.monty.io_snapshots.yaml
  - bases/logging.monty.io_recurringsnapshots.yaml
  #- bases/logging.monty.io_collectorconfigs.yaml
  - bases/monitoring.monty.io_rolebindings.yaml
  - bases/monitoring.monty.io_roles.yaml
  #- bases/monitoring.monty.io_collectorconfigs.yaml
  - bases/logging.monty.io_preprocessors.yaml

# +kubebuilder:scaffold:crdkustomizeresource

#patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_montyclusters.yaml
# - patches/webhook_in_montydemoes.yaml
#- patches/webhook_in_logadapters.yaml
#- patches/webhook_in_pretrainedmodels.yaml
#- patches/webhook_in_gpupolicyadapters.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_montyclusters.yaml
#- patches/cainjection_in_montydemoes.yaml
#- patches/cainjection_in_logadapters.yaml
#- patches/cainjection_in_pretrainedmodels.yaml
#- patches/cainjection_in_gpupolicyadapters.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
