lint = true
test = true

[releaser]
	repo = "github.com/aity-cloud/monty"
	os = ["darwin", "linux"]
	arch = ["amd64"]

[charts.git]
	repo = "github.com/aity-cloud/monty"
	branch = "charts-repo"
[charts.git.auth]
	email = "rancherbot@rancher.com"
	username = "Rancher Bot"

[charts.oci]
	repo = "registry.aity.tech/monty"

[images.monty]
	repo = "registry.aity.tech/monty/monty"

[images.minimal]
	repo = "registry.aity.tech/monty/monty"
	tag-suffix = "-minimal"

[images.opensearch.build]
	dashboards-version = "2.8.0"
	opensearch-version = "2.8.0"
	plugin-version = "0.12.1"

[images.opensearch.dashboards]
	repo = "registry.aity.tech/monty/opensearch-dashboards"
	tag-suffix = "-2.8.0"

[images.opensearch.opensearch]
	repo = "registry.aity.tech/monty/opensearch"
	tag-suffix = "-2.8.0"

[images.opensearch.update-service]
	repo = "registry.aity.tech/monty/monty-opensearch-update-service"

[images.python-base]
	repo = "registry.aity.tech/monty/monty-python-base"
	tag = "3.9"

[images.python-torch]
	repo = "registry.aity.tech/monty/monty-python-base"
	tag = "3.9"
	tag-suffix = "-torch"
