annotations:
  catalog.cattle.io/auto-install: monty-crd=match
  catalog.cattle.io/display-name: Monty
  catalog.cattle.io/os: linux
  catalog.cattle.io/namespace: monty
  catalog.cattle.io/release-name: monty
apiVersion: v2
appVersion: 0.12.1
dependencies:
- condition: monty-agent.kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: file://./charts/kube-prometheus-stack
- condition: monty-agent.enabled
  name: monty-agent
  repository: file://./charts/monty-agent
- condition: prometheus-crds.enabled
  name: prometheus-crds
  repository: file://./charts/prometheus-crds
description: Multi Cluster Observability with AIOps
icon: https://raw.githubusercontent.com/rancher/monty-docs/main/docs/assets/icon-monty.svg
keywords:
- monty
- monitoring
- logging
- rancher
- observability
maintainers:
- email: joe.kralicky@suse.com
  name: Joe Kralicky
- email: dan.bason@suse.com
  name: Dan Bason
name: monty
type: application
version: 0.12.1
