{
 "title": "Monty Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gateway Sample Ingestion Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(__tenant_id__) (rate(monty_gateway_remote_write_cluster_ingest_bytes_total[5m])) * on(__tenant_id__) group_left(friendly_name) (monty_cluster_info @ end())",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Gateway HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(rate(monty_gateway_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Workload Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{namespace=\"monty\"}[$__rate_interval])\n* on (pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"monty\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Workload Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{namespace=\"monty\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"monty\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Workload CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"monty\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"monty\"}\n) by (workload)\n",
     "legendFormat": "{{workload}} "
    }
   ]
  },
  {
   "title": "Workload Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"monty\", container!=\"\", image!=\"\"}\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"monty\"}\n) by (workload)\n",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}